spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/keycloak_prod
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: INFO